import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
import pandas as pd

def send_breakout_email(df, excel_path="Final_Breakout_List.xlsx", recipient_email=None, gmail_user=None, gmail_app_password=None):
    """
    Sends Positive Breakout Report to Gmail with HTML summary table and Excel attachment.
    """
    gmail_user = gmail_user or os.environ.get('GMAIL_USER')
    gmail_app_password = gmail_app_password or os.environ.get('GMAIL_APP_PASSWORD')
    recipient_email = recipient_email or os.environ.get('RECIPIENT_EMAIL') or gmail_user
    
    if not gmail_user or not gmail_app_password:
        print("⚠️ Email credentials missing. Set GMAIL_USER and GMAIL_APP_PASSWORD environment variables.")
        return False
        
    msg = MIMEMultipart('alternative')
    msg['From'] = f"Stock Screener <{gmail_user}>"
    msg['To'] = recipient_email
    
    date_str = pd.Timestamp.now().strftime("%d-%m-%Y")
    count = len(df) if df is not None and not df.empty else 0
    
    msg['Subject'] = f"📈 [{date_str}] Daily Stock Screener: {count} Positive Breakouts Found"
    
    # Construct HTML body
    table_html = ""
    if df is not None and not df.empty:
        # Convert df to HTML
        table_html = df.to_html(index=False, classes='breakout-table', border=0)
    else:
        table_html = "<p style='color: #64748b; font-style: italic;'>No stocks passed all breakout criteria today.</p>"
        
    html_content = f"""
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; background-color: #f8fafc; color: #1e293b; padding: 20px; }}
            .container {{ max-width: 800px; background: #ffffff; padding: 24px; border-radius: 8px; border: 1px solid #e2e8f0; }}
            h2 {{ color: #0f172a; border-bottom: 2px solid #10b981; padding-bottom: 8px; }}
            .badge {{ background-color: #d1fae5; color: #065f46; padding: 4px 8px; border-radius: 4px; font-weight: bold; }}
            table.breakout-table {{ width: 100%; border-collapse: collapse; margin-top: 16px; font-size: 13px; }}
            table.breakout-table th {{ background-color: #0f172a; color: #ffffff; padding: 10px; text-align: left; }}
            table.breakout-table td {{ padding: 10px; border-bottom: 1px solid #e2e8f0; }}
            table.breakout-table tr:nth-child(even) {{ background-color: #f8fafc; }}
            .footer {{ font-size: 12px; color: #94a3b8; margin-top: 24px; text-align: center; }}
        </style>
    </head>
    <body>
        <div class="container">
            <h2>📈 Daily CAR + 30/50/200 DMA Breakout Report</h2>
            <p><strong>Date:</strong> {date_str}</p>
            <p><strong>Breakout Stocks Found:</strong> <span class="badge">{count} Stocks</span></p>
            
            <h3>Breakout Summary</h3>
            {table_html}
            
            <p style="margin-top: 20px;">📎 Attached Excel file: <code>Final_Breakout_List.xlsx</code></p>
            
            <div class="footer">
                Automated report generated by Stock Screener • Configured for user digant2207
            </div>
        </div>
    </body>
    </html>
    """
    
    msg.attach(MIMEText(html_content, 'html'))
    
    # Attach Excel file if present
    if os.path.exists(excel_path):
        with open(excel_path, 'rb') as f:
            part = MIMEBase('application', 'octet-stream')
            part.set_payload(f.read())
            encoders.encode_base64(part)
            part.add_header('Content-Disposition', f'attachment; filename="{os.path.basename(excel_path)}"')
            msg.attach(part)
            
    try:
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(gmail_user, gmail_app_password)
        server.sendmail(gmail_user, recipient_email, msg.as_string())
        server.quit()
        print(f"✅ Email successfully sent to {recipient_email}!")
        return True
    except Exception as e:
        print(f"❌ Failed to send email: {e}")
        return False
